author: "tensorknower69"
category: Graphics
copyright: "2020-2022 tensorknower69"
synopsis: "A simple GPipe example program"
github: "tensorknower69/gpipe-example"
license: MIT
maintainer: "tensorknower69 <latesight20@protonmail.com>"
name: gpipe-example
version: 0.1.0.0

extra-source-files:
  - README.md

executables:
  gpipe-example:
    main: Main.hs
    source-dirs: app
    dependencies:
      - base >= 4.12
      - GPipe 
      - GPipe-GLFW
      - random
      - linear
      - transformers
      - exceptions
      - lens
    ghc-options:
      - -Wall
      - -Wno-tabs
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
